force-app/main/default/objects/Title__c/Title__c.object-meta.xml
<CustomObject>
    <label>Title</label>
    <nameField>
        <label>Title Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Titles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Title__c/fields/Available_Stock__c.field-meta.xml
<CustomField>
    <fullName>Available_Stock__c</fullName>
    <label>Available Stock</label>
    <summaryFilterItems>
        <field>Stock__c.Status__c</field>
        <operation>equals</operation>
        <value>Available</value>
    </summaryFilterItems>
    <summaryForeignKey>Stock__c.Title__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Title__c/fields/Director__c.field-meta.xml
<CustomField>
    <fullName>Director__c</fullName>
    <label>Director</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Title__c/fields/Genre__c.field-meta.xml
<CustomField>
    <fullName>Genre__c</fullName>
    <description>This the description</description>
    <inlineHelpText>Please enter the movie genre</inlineHelpText>
    <label>Genre</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Action</fullName>
            </value>
            <value>
                <fullName>Horror</fullName>
            </value>
            <value>
                <fullName>Comedy</fullName>
            </value>
            <value>
                <fullName>Thriller</fullName>
            </value>
            <value>
                <fullName>Sci-Fi</fullName>
            </value>
            <value>
                <fullName>Drama</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Title__c/fields/Notable_Actors__c.field-meta.xml
<CustomField>
    <fullName>Notable_Actors__c</fullName>
    <label>Notable Actors</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Title__c/fields/Plot_Description__c.field-meta.xml
<CustomField>
    <fullName>Plot_Description__c</fullName>
    <label>Plot Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Title__c/fields/Poster__c.field-meta.xml
<CustomField>
    <fullName>Poster__c</fullName>
    <label>Poster</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Title__c/fields/Release_Date__c.field-meta.xml
<CustomField>
    <fullName>Release_Date__c</fullName>
    <description>Date of initial release</description>
    <label>Release Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Title__c/fields/Runtime__c.field-meta.xml
<CustomField>
    <fullName>Runtime__c</fullName>
    <description>Runtime stored in minutes</description>
    <label>Runtime</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Title__c/fields/Total_Stock__c.field-meta.xml
<CustomField>
    <fullName>Total_Stock__c</fullName>
    <label>Total Stock</label>
    <summaryForeignKey>Stock__c.Title__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Title__c/fields/Writer__c.field-meta.xml
<CustomField>
    <fullName>Writer__c</fullName>
    <description>Primary writer of the film</description>
    <label>Writer</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TitleAuraService.cls
public with sharing class TitleAuraService {
  @AuraEnabled
  public static List<Title__c> getLatestTitles(Integer limiter) {
    return [
      SELECT
        Name,
        Genre__c,
        Poster__c,
        Available_Stock__c,
        Total_Stock__c,
        Runtime__c,
        Notable_Actors__c,
        Director__c,
        Writer__c,
        Plot_Description__c,
        Release_Date__c
      FROM Title__c
      ORDER BY CreatedDate DESC
      LIMIT :limiter
    ];
  }

  @AuraEnabled
  public static List<Title__c> getOutOfStockTitles() {
    return [
      SELECT
        Name,
        Genre__c,
        Poster__c,
        Available_Stock__c,
        Total_Stock__c,
        Runtime__c,
        Notable_Actors__c,
        Director__c,
        Writer__c,
        Plot_Description__c,
        Release_Date__c
      FROM Title__c
      WHERE Available_Stock__c = 0
      ORDER BY CreatedDate DESC
    ];
  }

  @AuraEnabled
  public static List<Title__c> getNewAndFeaturedTitles() {
    return [
      SELECT Poster__c
      FROM Title__c
      WHERE CreatedDate > :Date.today().addDays(-7)
    ];
  }
}