force-app/main/default/objects/Title__c/Title__c.object-meta.xml
<CustomObject>
    <label>Title</label>
    <nameField>
        <label>Title Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Titles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Title__c/fields/Director__c.field-meta.xml
<CustomField>
    <fullName>Director__c</fullName>
    <label>Director</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Title__c/fields/Notable_Actors__c.field-meta.xml
<CustomField>
    <fullName>Notable_Actors__c</fullName>
    <label>Notable Actors</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Title__c/fields/Writer__c.field-meta.xml
<CustomField>
    <fullName>Writer__c</fullName>
    <description>Primary writer of the film</description>
    <label>Writer</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AdvancedSearchController.cls
public class AdvancedSearchController {
 		  
    @AuraEnabled
    public static List<Title__c> getTitleList(String fieldName, String searchVal){
       	 String MOVIE_TITLE = 'Movie Title';
         String ACTOR = 'Actor';
         String DIRECTOR = 'Director';
         String WRITER = 'Writer';
        
        List<Title__c> titleList = new List<Title__c>();
        String val = '%'+searchVal+'%';
       
        Switch on fieldName{
            when 'Movie Title'{
                try{
                    titleList = [SELECT Id, Name 
                             FROM Title__c 
                             WHERE Name 
                             LIKE :val];
                }
                 catch(Exception e){
                    system.debug('AdvancedSearchController Error: '+e);
                }
                
            }
            when 'Actor'{
                try{
                    titleList = [SELECT Id, Name 
                             FROM Title__c 
                             WHERE Notable_Actors__c 
                             LIKE :val];
                } 
                catch(Exception e){
                    system.debug('AdvancedSearchController Error: '+e);
                }
                
            }
            when 'Director'{
                try{ 
                    titleList = [SELECT Id, Name 
                             FROM Title__c 
                             WHERE Director__c 
                             LIKE :val];
                }
                catch(Exception e){
                    system.debug('AdvancedSearchController Error: '+e);
                }
            }
            when 'Writer'{
                try{
                    titleList = [SELECT Id, Name 
                             FROM Title__c 
                             WHERE Writer__c 
                             LIKE :val];
                }
                 catch(Exception e){
                    system.debug('AdvancedSearchController Error: '+e);
                }
                
            }
            when else{
                try{
                    titleList = [SELECT Id, Name 
                             FROM Title__c 
                             WHERE Name LIKE: val
                             OR Notable_Actors__c LIKE: val
                             OR Writer__c LIKE: val
                             OR Director__c LIKE: val];
                }
                catch(Exception e){
                    system.debug('AdvancedSearchController Error: '+e);
                }
                
            }
        }
        return titleList;
    }
}