force-app/main/default/objects/Title__c/Title__c.object-meta.xml
<CustomObject>
    <label>Title</label>
    <nameField>
        <label>Title Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Titles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Title__c/fields/Average_Rating__c.field-meta.xml
<CustomField>
    <fullName>Average_Rating__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Average Rating</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Title__c/fields/Genre__c.field-meta.xml
<CustomField>
    <fullName>Genre__c</fullName>
    <description>This the description</description>
    <inlineHelpText>Please enter the movie genre</inlineHelpText>
    <label>Genre</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Action</fullName>
            </value>
            <value>
                <fullName>Horror</fullName>
            </value>
            <value>
                <fullName>Comedy</fullName>
            </value>
            <value>
                <fullName>Thriller</fullName>
            </value>
            <value>
                <fullName>Sci-Fi</fullName>
            </value>
            <value>
                <fullName>Drama</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Title__c/fields/Poster__c.field-meta.xml
<CustomField>
    <fullName>Poster__c</fullName>
    <label>Poster</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Title__c/fields/Release_Date__c.field-meta.xml
<CustomField>
    <fullName>Release_Date__c</fullName>
    <description>Date of initial release</description>
    <label>Release Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/BrowseAllFiltered.cls
public with sharing class BrowseAllFiltered {

    @AuraEnabled
    public static List<Title__c> getFilteredTitles(String genre, String orderBy) {
        List<Title__c> filteredTitles = new List<Title__c>();
        List<Title__c> allTitles = new List<Title__c>();

        if (orderBy == 'Release Date') {
            allTitles = [SELECT Name, Genre__c, Poster__c
                        FROM Title__c
                        ORDER BY Release_Date__c DESC];
        } else {
            allTitles = [SELECT Name, Genre__c, Poster__c
                         FROM TITLE__c
                         ORDER BY Average_Rating__c DESC];
        }

        for (Title__c t : allTitles) {
            if (t.Genre__c != null) {
                String[] genres = t.Genre__c.split(';');

                for (String s : genres) {
                    if (s == genre) {
                        filteredTitles.add(t);
                    }
                }
            }
        }
        system.debug(filteredTitles);
        return filteredTitles;
    }

    @AuraEnabled
    public static void getTitles() {

    }
}