force-app/main/default/objects/Rental__c/Rental__c.object-meta.xml
<CustomObject>
    <label>Rental</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>Rental Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rentals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Rental__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Rentals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Rental__c/fields/Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Due_Date__c</fullName>
    <label>Due Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Rental__c/fields/Stock__c.field-meta.xml
<CustomField>
    <fullName>Stock__c</fullName>
    <label>Stock</label>
    <referenceTo>Stock__c</referenceTo>
    <relationshipLabel>Rentals</relationshipLabel>
    <relationshipName>Rentals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Rental__c/fields/Title_Name__c.field-meta.xml
<CustomField>
    <fullName>Title_Name__c</fullName>
    <formula>Stock__r.Title_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Title Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Stock__c/Stock__c.object-meta.xml
<CustomObject>
    <label>Stock</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Stock Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stock</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Stock__c/fields/Title_Name__c.field-meta.xml
<CustomField>
    <fullName>Title_Name__c</fullName>
    <formula>Title__r.Name</formula>
    <label>Title Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/RentalController.cls
public class RentalController {
    
    @AuraEnabled
    public static List<RentalWrapper> getUserRentals(){
        /*Create a new Lightning Web Component called rentedTitlesList
         * Display the Due Date, Title, and Poster of each title the current User currently has an open Rental for
         * The Due Date should be Red when Overdue.
        */
        List<RentalWrapper> overDueRentalList = new List<RentalWrapper>();
        List<Rental__c> userRentals = [Select Id, Name, Due_Date__c, Stock__r.Title_Name__c, Stock__r.Poster__c FROM Rental__c WHERE Customer__c =: UserInfo.getUserId()];
        
        for( Rental__c r : userRentals){
            system.debug(r);
            overDueRentalList.add(new RentalWrapper(r));
        }

        system.debug(overDueRentalList);
        return overDueRentalList;
    }
}


//System.debug(RentalController.getUserRentals(UserInfo.GETUSERID()));