force-app/main/default/objects/Rental__c/Rental__c.object-meta.xml
<CustomObject>
    <label>Rental</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>Rental Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rentals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Rental__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Rentals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Rental__c/fields/Stock__c.field-meta.xml
<CustomField>
    <fullName>Stock__c</fullName>
    <label>Stock</label>
    <referenceTo>Stock__c</referenceTo>
    <relationshipLabel>Rentals</relationshipLabel>
    <relationshipName>Rentals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Stock__c/Stock__c.object-meta.xml
<CustomObject>
    <label>Stock</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Stock Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stock</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Stock__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <label>Title</label>
    <referenceTo>Title__c</referenceTo>
    <relationshipLabel>Stock</relationshipLabel>
    <relationshipName>Stock</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Title__c/Title__c.object-meta.xml
<CustomObject>
    <label>Title</label>
    <nameField>
        <label>Title Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Titles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Title__c/fields/Genre__c.field-meta.xml
<CustomField>
    <fullName>Genre__c</fullName>
    <description>This the description</description>
    <inlineHelpText>Please enter the movie genre</inlineHelpText>
    <label>Genre</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Action</fullName>
            </value>
            <value>
                <fullName>Horror</fullName>
            </value>
            <value>
                <fullName>Comedy</fullName>
            </value>
            <value>
                <fullName>Thriller</fullName>
            </value>
            <value>
                <fullName>Sci-Fi</fullName>
            </value>
            <value>
                <fullName>Drama</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Title__c/fields/Poster__c.field-meta.xml
<CustomField>
    <fullName>Poster__c</fullName>
    <label>Poster</label>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/RecommendedMovies.cls
public with sharing class RecommendedMovies {
    
    @AuraEnabled
    public static List<Title__c> getRecommendedTitles(){
        /**
         * Retreive movies to be diplayed in the recommneded movies lightning web component
         * Recommneded movies should share a genre with another movie the user has rented
         */
        List<Title__c> recommendedMoviesList = new List<Title__c>();
        List<Rental__c> userRentals = [SELECT Stock__r.Title__r.Genre__c
                                       FROM Rental__c
                                       WHERE Customer__c =: UserInfo.getUserId()];
        List<Title__c> allTitles = [SELECT Name, Genre__c, Poster__c
                                    FROM Title__c];

        Set<String> myGenres = new Set<String>();
        for (Rental__c myRental : userRentals) {
            myGenres.addAll(myRental.Stock__r.Title__r.Genre__c.split(';'));
            
        }

        for (Title__c t : allTitles) {
            if (t.Genre__c != null ) {
                String[] genres = t.Genre__c.split(';');

                boolean hasGenre = false;
                for (String genre : genres) {
                    if (myGenres.contains(genre)) {
                        hasGenre = true;
                    }
                }
                if (hasGenre) {
                    recommendedMoviesList.add(t);
                }
            }
        }

        return recommendedMoviesList;
    }
}