force-app/main/default/objects/Stock__c/Stock__c.object-meta.xml
<CustomObject>
    <label>Stock</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Stock Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stock</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Stock__c/fields/Damage_Description__c.field-meta.xml
<CustomField>
    <fullName>Damage_Description__c</fullName>
    <label>Damage Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Stock__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>Rented</fullName>
            </value>
            <value>
                <fullName>Damaged</fullName>
            </value>
            <value>
                <fullName>Missing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Stock__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <label>Title</label>
    <referenceTo>Title__c</referenceTo>
    <relationshipLabel>Stock</relationshipLabel>
    <relationshipName>Stock</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Title__c/Title__c.object-meta.xml
<CustomObject>
    <label>Title</label>
    <nameField>
        <label>Title Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Titles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/DamagedRentalCaseGeneratorTest.cls
@isTest
private class DamagedRentalCaseGeneratorTest {
    @TestSetup
    static void setupStockData(){
        Title__c testTitle = TestDataFactory.createTitle('Test Movie', 'Action');
        insert testTitle;

        Stock__c testStock = TestDataFactory.createStock(testTitle.Id, 'Available');
        insert testStock; 

        Stock__c testStock2 = TestDataFactory.createStock(testTitle.Id, 'Available');
        insert testStock2; 

        Stock__c testStock3 = TestDataFactory.createStock(testTitle.Id, 'Available');
        insert testStock3; 
  
    

    }

    @isTest
    static void generateCasesForDamagedUpdatedStock_givenADamagedStock_shouldGenerateACase() {

        List<Stock__c> testStock = [SELECT Status__c FROM Stock__c];

        Test.startTest();

        testStock[0].Status__c = 'Damaged';
        testStock[0].Damage_Description__c = 'Its sctrached';
        update testStock[0];

        Test.stopTest();

        List<Case> generatedCases = [SELECT Id FROM Case];
        System.assertEquals(1, generatedCases.size(), 'One case should have been generated');

    }


    @isTest
    static void generateCasesForDamagedUpdatedStock_givenMultipleDamagedStock_shouldGenerateMultipleCases() {

        List<Stock__c> testStock = [SELECT Status__c FROM Stock__c];
        List<Stock__c> stockToUpdate = new List<Stock__c>();

        Test.startTest();

        for (integer i = 0; i<3; i++)
        {

            testStock[i].Status__c = 'Damaged';
            testStock[i].Damage_Description__c = 'Its sctrached';
            stockToUpdate.add(testStock[i]);
        }
        update stockToUpdate;

        Test.stopTest();

        List<Case> generatedCases = [SELECT Id FROM Case];
        System.assertEquals(3, generatedCases.size(), 'Three cases should have been generated');

    }

    @isTest
    static void generateCasesForDamagedUpdatedStock_givenANonDamagedStock_shouldNotGenerateACase() {

        List<Stock__c> testStock = [SELECT Status__c FROM Stock__c];

        Test.startTest();

        testStock[0].Status__c = 'Rented';
        update testStock[0];

        Test.stopTest();

        List<Case> generatedCases = [SELECT Id FROM Case];
        System.assertEquals(0, generatedCases.size(), 'No cases should have been generated');

    }

 
    @isTest
    static void generateCasesForDamagedInsertedStock_givenAnInsertedDamageStock_shouldGenerateACase() {

        Title__c testTitle = TestDataFactory.createTitle('Test', 'Action');
        insert testTitle;

        Test.startTest();
        Stock__c s = new Stock__c();
        s.Title__c = testTitle.id;
        s.Status__c = 'Damaged';
        s.Damage_Description__c = 'Test-Damage';
       
        insert s;

        Test.stopTest();

        List<Case> generatedCases = [SELECT Id FROM Case];
        System.assertEquals(1, generatedCases.size(), 'One case should have been generated');

    }


}