force-app/main/default/objects/Stock__c/Stock__c.object-meta.xml
<CustomObject>
    <label>Stock</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Stock Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stock</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Stock__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>Rented</fullName>
            </value>
            <value>
                <fullName>Damaged</fullName>
            </value>
            <value>
                <fullName>Missing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Stock__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <label>Title</label>
    <referenceTo>Title__c</referenceTo>
    <relationshipLabel>Stock</relationshipLabel>
    <relationshipName>Stock</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Title__c/Title__c.object-meta.xml
<CustomObject>
    <label>Title</label>
    <nameField>
        <label>Title Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Titles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/StockControllerTest.cls
@isTest
private class StockControllerTest {
  @TestSetup
  static void setupStockData() {
    Title__c testTitle = TestDataFactory.createTitle('Test Movie', 'Action');
    insert testTitle;

    Stock__c testStock = TestDataFactory.createStock(testTitle.Id, 'Available');
    insert testStock;

    Stock__c testStock2 = TestDataFactory.createStock(testTitle.Id, 'Rented');
    insert testStock2;

    Stock__c testStock3 = TestDataFactory.createStock(testTitle.Id, 'Damaged');
    insert testStock3;
  }

  @isTest
  static void rentStock_givenAnAvailableStock_shouldChangeStatusToRented() {
    List<Stock__c> testStock = [SELECT Status__c FROM Stock__c];
    List<Stock__c> stockToUpdate = new List<Stock__c>();

    StockController.rentStock(testStock[0]);

    testStock = [SELECT Status__c FROM Stock__c];
    System.assertEquals(
      'Rented',
      testStock[0].Status__c,
      'Stock Status Should be rented'
    );
  }

  @isTest
  static void rentStock_givenARentedStock_statusShouldRemainRented() {
    List<Stock__c> testStock = [SELECT Status__c FROM Stock__c];
    List<Stock__c> stockToUpdate = new List<Stock__c>();

    StockController.rentStock(testStock[1]);

    testStock = [SELECT Status__c FROM Stock__c];
    System.assertEquals(
      'Rented',
      testStock[1].Status__c,
      'Stock Status Should be rented + Should go through error loop'
    );
  }

  @isTest
  static void rentStock_givenADamagedStock_shouldNotChangeStatusToRented() {
    List<Stock__c> testStock = [SELECT Status__c FROM Stock__c];
    List<Stock__c> stockToUpdate = new List<Stock__c>();

    StockController.rentStock(testStock[2]);

    testStock = [SELECT Status__c FROM Stock__c];
    System.assertEquals(
      'Damaged',
      testStock[2].Status__c,
      'Should Remain Damaged'
    );
  }
}