force-app/main/default/objects/Stock__c/Stock__c.object-meta.xml
<CustomObject>
    <label>Stock</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Stock Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stock</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Stock__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>Rented</fullName>
            </value>
            <value>
                <fullName>Damaged</fullName>
            </value>
            <value>
                <fullName>Missing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DamagedRentalCaseGenerator.cls
public with sharing class DamagedRentalCaseGenerator {
    public void generateCasesForDamagedUpdatedStock(List<Stock__c> updatedStock, 
    Map<Id, Stock__c> oldStockValueMap) {

    Database.DMLOptions dmlOpts = createDMLOptions();

    List<Case> generatedCases = new List<Case>();

    Case newCase;
   
        for(Stock__c s : updatedStock) {
        if(s.Status__c == 'Damaged' && oldStockValueMap.get(s.Id).Status__c != 'Damaged') {
            newCase = createDamageCase(newCase, s.Id);
            newCase.setOptions(dmlOpts);
            generatedCases.add(newCase);
            }
            
        }

    insert generatedCases;
    }

    public void generateCasesForDamagedInsertedStock(List<Stock__c> updatedStock) {

    Database.DMLOptions dmlOpts = createDMLOptions();

    List<Case> generatedCases = new List<Case>();

    Case newCase;
        for(Stock__c s : updatedStock) {
        if(s.Status__c == 'Damaged') {
            newCase = createDamageCase(newCase, s.Id);
            newCase.setOptions(dmlOpts);
            generatedCases.add(newCase);
            }
        }

    insert generatedCases;
    }

 

    private Case createDamageCase(Case newCase, Id stockID) {

    newCase = new Case();
    newCase.Stock__c = stockID;
    newCase.Status = 'New';
    newCase.Origin = 'Web';
    newCase.Subject = 'Maintenance Required';


    return newCase;

    }

    private Database.DMLOptions createDMLOptions() {

    //Fetching the assignment rules on case - Following Help article - https://help.salesforce.com/articleView?id=000338182&type=1&mode=1
    AssignmentRule AR = new AssignmentRule();
    AR = [select id from AssignmentRule where SobjectType = 'Case' and Active = true limit 1];

    //Creating the DMLOptions for "Assign using active assignment rules" checkbox
    Database.DMLOptions dmlOpts = new Database.DMLOptions();
    dmlOpts.assignmentRuleHeader.assignmentRuleId= AR.id;


    return dmlOpts;

    }
}